artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/MorningStarTM/raw-data/raw/main/drug_review.zip"
  local_data_file: artifacts/data_ingestion/data_review.zip
  unzip_dir: artifacts/data_ingestion
  

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "val", "data_review.zip"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/
  tokenizer_name: distilbert-base-uncased


model_trainer:
root_dir: artifacts/model_trainer
data_path: artifacts/data_transformation/drug_review
weights: artifacts/data_transformation/class_weights.json
model_ckpt: distilbert-base-uncased

